
title: comment-faire.modernisation.gouv.fr
description: >
  Des m√©thodes et outils pour transformer l'action publique
# Build settings
markdown: kramdown

baseurl: "/comment-faire"

collections:
  methodes:
    output: true
  outils:
    output: true
  articles:
    output: true
theme: jekyll-theme-minimal